[project]
name = "subseek"
version = "0.1.0"
description = "搜索GitHub仓库公开的节点和网络公开的节点"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests",
    "sqlalchemy",
    "pyyaml",
    "ddgs",
]
